# Generated by Django 4.2 on 2026-01-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Connection Name')),
                ('db_type', models.CharField(choices=[('mssql', 'Microsoft SQL Server'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle')], default='mssql', max_length=20)),
                ('host', models.CharField(max_length=200)),
                ('port', models.IntegerField(default=1433)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(help_text='Encrypted storage recommended', max_length=200)),
                ('db_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Source',
                'db_table': 'bi_datasource',
            },
        ),
    ]
