# Generated by Django 4.2 on 2026-01-27 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('platform', models.CharField(choices=[('pc', 'PC Browser'), ('mobile', 'Mobile App/H5')], default='pc', max_length=10)),
                ('template_config', models.TextField(default='{}', verbose_name='Visual Template Config')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datasets', models.ManyToManyField(blank=True, to='dataset.dataset')),
            ],
            options={
                'verbose_name': 'Report',
                'db_table': 'bi_report',
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cron_expression', models.CharField(help_text='Standard Cron format', max_length=100)),
                ('task_type', models.CharField(choices=[('email', 'Send Email'), ('cache', 'Refresh Cache')], max_length=50)),
                ('target_config', models.TextField(default='{}', help_text='Config for the task (e.g., report_id, email_list)')),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bi_scheduled_task',
            },
        ),
        migrations.CreateModel(
            name='ReportFunctionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_path', models.CharField(max_length=255, verbose_name='Backend Function Path')),
                ('is_active', models.BooleanField(default=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backend_mapping', to='reporting.report')),
            ],
            options={
                'verbose_name': 'Report Function Mapping',
                'db_table': 'bi_report_mapping',
            },
        ),
    ]
