# Generated by Django 4.2 on 2026-01-27 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Report'},
        ),
        migrations.AddField(
            model_name='report',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ReportDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='reporting.reportdirectory')),
            ],
            options={
                'verbose_name': 'Report Directory',
                'db_table': 'bi_report_directory',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reporting.reportdirectory'),
        ),
    ]
