# Generated by Django 4.2 on 2026-01-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_alter_report_options_report_sort_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Display in List'),
        ),
    ]
