# Generated by Django 4.2 on 2026-02-05 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='directories',
            field=models.ManyToManyField(blank=True, related_name='reports', to='reporting.reportdirectory', verbose_name='所属目录'),
        ),
        migrations.AlterField(
            model_name='report',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_legacy', to='reporting.reportdirectory'),
        ),
    ]
