# Generated by Django 4.2 on 2026-02-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_report_directories_alter_report_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='external_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='External URL'),
        ),
    ]
