# Generated by Django 4.2 on 2026-01-27 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Menu Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Permission Code')),
                ('path', models.CharField(blank=True, max_length=200, verbose_name='Frontend Path')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('is_report_dir', models.BooleanField(default=False, verbose_name='Is Report Directory')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_auth.sysmenu', verbose_name='Parent Menu')),
            ],
            options={
                'verbose_name': 'System Menu',
                'db_table': 'sys_menu',
            },
        ),
        migrations.CreateModel(
            name='SysRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('menus', models.ManyToManyField(blank=True, to='core_auth.sysmenu', verbose_name='Menu Permissions')),
            ],
            options={
                'db_table': 'sys_role',
            },
        ),
        migrations.CreateModel(
            name='SysDataPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100, verbose_name='Target Table')),
                ('filter_rule', models.TextField(help_text='e.g., dept_id = {user.dept_id}', verbose_name='SQL Filter Condition')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_auth.sysrole')),
            ],
            options={
                'db_table': 'sys_data_permission',
            },
        ),
    ]
