# Generated by Django 4.2 on 2026-01-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('username', models.CharField(max_length=150)),
                ('action_type', models.CharField(choices=[('LOGIN', 'Login'), ('QUERY', 'Query Data'), ('EXPORT', 'Export Report'), ('MODIFY', 'Modify System')], max_length=20)),
                ('target', models.CharField(help_text='Target object/report', max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sys_audit_log',
            },
        ),
    ]
